export const PublicationsActionTypes = {
    FETCH_PUBLICATIONS_START: 'FETCH_PUBLICATIONS_START',
    FETCH_PUBLICATIONS_SUCCESS: 'FETCH_PUBLICATIONS_SUCCESS',
    FETCH_PUBLICATIONS_FAIL: 'FETCH_PUBLICATIONS_FAIL'
}